spring:
  application:
    name: BigBoard

#  h2:
#    console:
#      path: /h2-console
#      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: devuser
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:file:/Users/gimmingyu/MyProjects/db/DB
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework.cache: trace #Redis 사용에 대한 로그가 조회되도록 설정
      hibernate.type.descriptor.sql.BasicBinder: TRACE